#here we are installing the mysql server in one of the server without logining into the server 

- name: install and run the mysql on node1
  host: roboshop-us-dev-db-mysql-01.nishaldevops.online
  become: yes
  tasks: 
  - name: install mysql
    ansible.builtin.yum:
      name: mysql
      state: installed
  - name: start mysql
    ansible.builtin.service: 
      name: mysql
      state: started

      
