- name: here we are doing to prompt the user while he use to enter the user credentials while login
  hosts: localhost
  vars_prompt:

  - name: username
    prompt: "What is your username?"
    private: false

  - name: password
    prompt: "What is your password?"
    private: true #true is we are hiding the password for confidential

  tasks:
  - name : print username and password variables
    ansible.builtin.debug:
      msg: "username: {{USERNAME}}, password: {{PASSWORD}}" 

