- name: install multiple packages
  hosts: localhost
  become: yes
  tasks: 

  - name: install package
    ansible.builtin.yum: 
      name: "{{item}}"
      state: installed
    
    loop: 
    - nginx
    - postfix


    
