- name: install multiple packages
  hosts: localhost
  become: yes
  tasks: 

  - name: install packages
    ansible.builtin.yum: 
      name: "{{installed}}"
      state: installed
    
    loop: 
    - nginx
    - postfix


    
