- name: install multiple packages
  hosts: mongodb
  become: yes
  tasks: 

  - name: install package
    ansible.builtin.yum: 
      name: "{{item.name}}"
      state: "{{item.state}}"

      #list of map
    
    loop: 
    - {name: ''nginx', state: 'absent'}
    - {name: 'postfix', state: 'installed'}
    - {name: 'mailx', state: 'absent'}
