- name: installing  http, git using this ansible playbook 
  hosts: node1
  become: yes
  tasks: 

  # - name: install git
  #   ansible.builtin.yum: 
  #     name: git
  #     state: installed
  # # - name: start git
  # #   ansible.builtin.service: 
  # #     name: git 
  # #     state: started

  # - name: install httpd
  #   ansible.builtin.yum: 
  #     name: httpd
  #     state: installed
  # - name: start httpd
  #   ansible.builtin.service: 
  #     name: httpd
  #     state: started


    #----------------------------------------------------------------by using loops------------------------------

  - name: install multiple packages
    ansible.builtin.yum: 
      name: "{{item}}"
      state: installed

      loops: 
      - nginx
      - tomcat 
      - apache






