- name: installing  http, git using this ansible playbook 
  hosts: node1
  become: yes
  tasks: install git and http

  - name: install git and http
    ansible.builtin.yum: 
      name: http
      state: installed


