- name: installing  http, git using this ansible playbook 
  hosts: node1
  become: yes
  tasks: install git and http

  - name: install git
    ansible.builtin.yum: 
      name: git
      state: installed


