- name: installing  http, git using this ansible playbook 
  hosts: node1
  become: yes
  tasks: 

  - name: install git
    ansible.builtin.yum: 
      name: git
      state: installed
  - name: start git
    ansible.builtin.service: 
      name: git 
      state: started

  # - name: install http
  #   ansible.builtin.yum: 
  #     name: http
  #     state: installed
  #   ansible.builtin.service: 
  #     name: http
  #     state: started




